export const PermissionConstants = {
  PERM_REMOVE_USER: "PERM_REMOVE_USER",
  PERM_CREATE_USER: "PERM_CREATE_USER",
  PERM_UPDATE_USER: "PERM_UPDATE_USER",
  PERM_VIEW_USER: "PERM_VIEW_USER",

  PERM_CREATE_ROLE: "PERM_CREATE_ROLE",
  PERM_UPDATE_ROLE: "PERM_UPDATE_ROLE",
  PERM_REMOVE_ROLE: "PERM_REMOVE_ROLE",
  PERM_VIEW_ROLE: "PERM_VIEW_ROLE",

  PERM_CREATE_PERMISSION: "PERM_CREATE_PERMISSION",
  PERM_UPDATE_PERMISSION: "PERM_UPDATE_PERMISSION",
  PERM_REMOVE_PERMISSION: "PERM_REMOVE_PERMISSION",
  PERM_VIEW_PERMISSION: "PERM_VIEW_PERMISSION",

  PERM_CREATE_CATEGORY: "PERM_CREATE_CATEGORY",
  PERM_UPDATE_CATEGORY: "PERM_UPDATE_CATEGORY",
  PERM_REMOVE_CATEGORY: "PERM_REMOVE_CATEGORY",
  PERM_VIEW_CATEGORY: "PERM_VIEW_CATEGORY",

  PERM_CREATE_UNIT: "PERM_CREATE_UNIT",
  PERM_UPDATE_UNIT: "PERM_UPDATE_UNIT",
  PERM_REMOVE_UNIT: "PERM_REMOVE_UNIT",
  PERM_VIEW_UNIT: "PERM_VIEW_UNIT",

  PERM_CREATE_ASSET: "PERM_CREATE_ASSET",
  PERM_UPDATE_ASSET: "PERM_UPDATE_ASSET",
  PERM_VIEW_ASSET: "PERM_VIEW_ASSET",
  PERM_REMOVE_ASSET: "PERM_REMOVE_ASSET",
  PERM_IDENTIFY_ASSET: "PERM_IDENTIFY_ASSET",
  PERM_UPDATE_RFID: "PERM_UPDATE_RFID",
  PERM_REMOVE_RFID: "PERM_REMOVE_RFID",
  PERM_IMPORT_ASSET: "PERM_IMPORT_ASSET",

  PERM_CREATE_INVENTORY: "PERM_CREATE_INVENTORY",
  PERM_UPDATE_INVENTORY: "PERM_UPDATE_INVENTORY",
  PERM_VIEW_INVENTORY: "PERM_VIEW_INVENTORY",
  PERM_VIEW_RESULT_INVENTORY: "PERM_VIEW_RESULT_INVENTORY",
  PERM_REMOVE_INVENTORY: "PERM_REMOVE_INVENTORY",
  PERM_PERFORM_INVENTORY: "PERM_PERFORM_INVENTORY",

  PERM_VIEW_ALERT: "PERM_VIEW_ALERT",
  PERM_RESOLVE_ALERT: "PERM_RESOLVE_ALERT",

  PERM_CREATE_LIQUIDATION: "PERM_CREATE_LIQUIDATION",
  PERM_UPDATE_LIQUIDATION: "PERM_UPDATE_LIQUIDATION",
  PERM_VIEW_LIQUIDATION: "PERM_VIEW_LIQUIDATION",
  PERM_REMOVE_LIQUIDATION: "PERM_REMOVE_LIQUIDATION",
  PERM_PROPOSED_LIQUIDATION: "PERM_PROPOSED_LIQUIDATION",
  PERM_APPROVE_LIQUIDATION: "PERM_APPROVE_LIQUIDATION",
  PERM_REJECT_LIQUIDATION: "PERM_REJECT_LIQUIDATION",
  PERM_FINALIZED_LIQUIDATION: "PERM_FINALIZED_LIQUIDATION",

  PERM_CREATE_TRANSACTION: "PERM_CREATE_TRANSACTION",
  PERM_UPDATE_TRANSACTION: "PERM_UPDATE_TRANSACTION",
  PERM_VIEW_TRANSACTION: "PERM_VIEW_TRANSACTION",
  PERM_REMOVE_TRANSACTION: "PERM_REMOVE_TRANSACTION",
  PERM_PROPOSE_TRANSACTION: "PERM_PROPOSE_TRANSACTION",
  PERM_APPROVE_TRANSACTION: "PERM_APPROVE_TRANSACTION",
  PERM_REJECT_TRANSACTION: "PERM_REJECT_TRANSACTION",
  PERM_UPDATE_TRANSACTION_STATUS: "PERM_UPDATE_TRANSACTION_STATUS",
} as const;

export type Permission =
  (typeof PermissionConstants)[keyof typeof PermissionConstants];
