export const PermissionConstants = {
  // User Permissions
  PERM_CREATE_USER: 'PERM_CREATE_USER',
  PERM_UPDATE_USER: 'PERM_UPDATE_USER',
  PERM_VIEW_USER: 'PERM_VIEW_USER',
  PERM_REMOVE_USER: 'PERM_REMOVE_USER',

  // Role Permissions
  PERM_CREATE_ROLE: 'PERM_CREATE_ROLE',
  PERM_UPDATE_ROLE: 'PERM_UPDATE_ROLE',
  PERM_VIEW_ROLE: 'PERM_VIEW_ROLE',
  PERM_REMOVE_ROLE: 'PERM_REMOVE_ROLE',

  // Permission Permissions
  PERM_CREATE_PERMISSION: 'PERM_CREATE_PERMISSION',
  PERM_UPDATE_PERMISSION: 'PERM_UPDATE_PERMISSION',
  PERM_VIEW_PERMISSION: 'PERM_VIEW_PERMISSION',
  PERM_REMOVE_PERMISSION: 'PERM_REMOVE_PERMISSION',

  // Category Permissions
  PERM_CREATE_CATEGORY: 'PERM_CREATE_CATEGORY',
  PERM_UPDATE_CATEGORY: 'PERM_UPDATE_CATEGORY',
  PERM_VIEW_CATEGORY: 'PERM_VIEW_CATEGORY',
  PERM_REMOVE_CATEGORY: 'PERM_REMOVE_CATEGORY',

  // Unit Permissions
  PERM_CREATE_UNIT: 'PERM_CREATE_UNIT',
  PERM_UPDATE_UNIT: 'PERM_UPDATE_UNIT',
  PERM_VIEW_UNIT: 'PERM_VIEW_UNIT',
  PERM_REMOVE_UNIT: 'PERM_REMOVE_UNIT',

  // Room Permissions
  PERM_CREATE_ROOM: 'PERM_CREATE_ROOM',
  PERM_UPDATE_ROOM: 'PERM_UPDATE_ROOM',
  PERM_VIEW_ROOM: 'PERM_VIEW_ROOM',
  PERM_REMOVE_ROOM: 'PERM_REMOVE_ROOM',

  // Asset Permissions
  PERM_UPDATE_ASSET: 'PERM_UPDATE_ASSET',
  PERM_VIEW_ASSET: 'PERM_VIEW_ASSET',
  PERM_REMOVE_ASSET: 'PERM_REMOVE_ASSET',
  PERM_IDENTIFY_ASSET: 'PERM_IDENTIFY_ASSET',
  PERM_UPDATE_RFID: 'PERM_UPDATE_RFID',
  PERM_REMOVE_RFID: 'PERM_REMOVE_RFID',
  PERM_IMPORT_ASSET: 'PERM_IMPORT_ASSET',

  // Inventory Permissions
  PERM_CREATE_INVENTORY: 'PERM_CREATE_INVENTORY',
  PERM_UPDATE_INVENTORY: 'PERM_UPDATE_INVENTORY',
  PERM_VIEW_INVENTORY: 'PERM_VIEW_INVENTORY',
  PERM_REMOVE_INVENTORY: 'PERM_REMOVE_INVENTORY',

  // Inventory Group Permissions
  PERM_CREATE_INVENTORY_GROUP: 'PERM_CREATE_INVENTORY_GROUP',
  PERM_UPDATE_INVENTORY_GROUP: 'PERM_UPDATE_INVENTORY_GROUP',
  PERM_VIEW_INVENTORY_GROUP: 'PERM_VIEW_INVENTORY_GROUP',
  PERM_REMOVE_INVENTORY_GROUP: 'PERM_REMOVE_INVENTORY_GROUP',
  PERM_ASSIGN_INVENTORY_GROUP: 'PERM_ASSIGN_INVENTORY_GROUP',
  PERM_MANAGE_GROUP_MEMBERS: 'PERM_MANAGE_GROUP_MEMBERS',

  // Inventory Sub Permissions
  PERM_CREATE_INVENTORY_SUB: 'PERM_CREATE_INVENTORY_SUB',
  PERM_UPDATE_INVENTORY_SUB: 'PERM_UPDATE_INVENTORY_SUB',
  PERM_VIEW_INVENTORY_SUB: 'PERM_VIEW_INVENTORY_SUB',
  PERM_REMOVE_INVENTORY_SUB: 'PERM_REMOVE_INVENTORY_SUB',
  PERM_MANAGE_SUB_MEMBERS: 'PERM_MANAGE_SUB_MEMBERS',

  // Inventory Committee Permissions
  PERM_APPROVE_INVENTORY_RESULT: 'PERM_APPROVE_INVENTORY_RESULT',
  PERM_REVIEW_INVENTORY_REPORT: 'PERM_REVIEW_INVENTORY_REPORT',
  PERM_FINALIZE_INVENTORY: 'PERM_FINALIZE_INVENTORY',
} as const

// Type for permission values
export type Permission = typeof PermissionConstants[keyof typeof PermissionConstants]

// Permission groups for easier management
export const PermissionGroups = {
  USER: [
    PermissionConstants.PERM_CREATE_USER,
    PermissionConstants.PERM_UPDATE_USER,
    PermissionConstants.PERM_VIEW_USER,
    PermissionConstants.PERM_REMOVE_USER,
  ],
  ROLE: [
    PermissionConstants.PERM_CREATE_ROLE,
    PermissionConstants.PERM_UPDATE_ROLE,
    PermissionConstants.PERM_VIEW_ROLE,
    PermissionConstants.PERM_REMOVE_ROLE,
  ],
  CATEGORY: [
    PermissionConstants.PERM_CREATE_CATEGORY,
    PermissionConstants.PERM_UPDATE_CATEGORY,
    PermissionConstants.PERM_VIEW_CATEGORY,
    PermissionConstants.PERM_REMOVE_CATEGORY,
  ],
  UNIT: [
    PermissionConstants.PERM_CREATE_UNIT,
    PermissionConstants.PERM_UPDATE_UNIT,
    PermissionConstants.PERM_VIEW_UNIT,
    PermissionConstants.PERM_REMOVE_UNIT,
  ],
  ROOM: [
    PermissionConstants.PERM_CREATE_ROOM,
    PermissionConstants.PERM_UPDATE_ROOM,
    PermissionConstants.PERM_VIEW_ROOM,
    PermissionConstants.PERM_REMOVE_ROOM,
  ],
  ASSET: [
    PermissionConstants.PERM_UPDATE_ASSET,
    PermissionConstants.PERM_VIEW_ASSET,
    PermissionConstants.PERM_REMOVE_ASSET,
    PermissionConstants.PERM_IDENTIFY_ASSET,
    PermissionConstants.PERM_UPDATE_RFID,
    PermissionConstants.PERM_REMOVE_RFID,
    PermissionConstants.PERM_IMPORT_ASSET,
  ],
  INVENTORY: [
    PermissionConstants.PERM_CREATE_INVENTORY,
    PermissionConstants.PERM_UPDATE_INVENTORY,
    PermissionConstants.PERM_VIEW_INVENTORY,
    PermissionConstants.PERM_REMOVE_INVENTORY,
  ],
  INVENTORY_GROUP: [
    PermissionConstants.PERM_CREATE_INVENTORY_GROUP,
    PermissionConstants.PERM_UPDATE_INVENTORY_GROUP,
    PermissionConstants.PERM_VIEW_INVENTORY_GROUP,
    PermissionConstants.PERM_REMOVE_INVENTORY_GROUP,
    PermissionConstants.PERM_ASSIGN_INVENTORY_GROUP,
    PermissionConstants.PERM_MANAGE_GROUP_MEMBERS,
  ],
  INVENTORY_SUB: [
    PermissionConstants.PERM_CREATE_INVENTORY_SUB,
    PermissionConstants.PERM_UPDATE_INVENTORY_SUB,
    PermissionConstants.PERM_VIEW_INVENTORY_SUB,
    PermissionConstants.PERM_REMOVE_INVENTORY_SUB,
    PermissionConstants.PERM_MANAGE_SUB_MEMBERS,
  ],
  INVENTORY_COMMITTEE: [
    PermissionConstants.PERM_APPROVE_INVENTORY_RESULT,
    PermissionConstants.PERM_REVIEW_INVENTORY_REPORT,
    PermissionConstants.PERM_FINALIZE_INVENTORY,
  ],
} as const
